mod_id=customjukeboxdiscs
mod_name=Custom Jukebox Discs
mod_version=0.2.8
mod_group=dev.hoodoo.customjukeboxdiscs
mod_authors=HooDoo
mod_description=Standalone, configurable music-disc upload and playback mod for Minecraft 1.12.2 Forge.
mod_license=MIT

minecraft_version=1.12.2
forge_version=14.23.5.2860
mcp_mappings=stable_39
